alias sublime='~/bin/sublimetext2/sublime_text'
alias apt-get='sudo apt-get'
alias netbeans='sh ~/netbeans-7.4/bin/netbeans'
alias startrvm='source ~/.rvm/scripts/rvm'
alias ls='ls -al --color'
alias rm='rm -rf'
alias jkl='jekyll serve --watch'
alias rsvr='rails server'
